### ISSUE TITLE
Grid thickness

### ISSUE THREAD

**Issue by jhdscript** [meandavejustice/canvas-grid#8]
Hello, Is it possible to reduce grid lines thickness ?

**Comment by meandavejustice** [comment]
This lib doesn't provide an argument to set the grid line thickness, you would need to set this on the [stroke](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/stroke).

Check out https://github.com/meandavejustice/canvas-grid/blob/master/index.js#L78 for where to make the stroke modification
